/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrackId = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Playlist = IDL.Vec(TrackId);

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getActivePlaylist' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
  'getPlaylist' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
  'getPlaylistByName' : IDL.Func([IDL.Text], [IDL.Vec(TrackId)], ['query']),
  'getPlaylistNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFavorites' : IDL.Func([IDL.Vec(TrackId)], [], []),
  'savePlaylist' : IDL.Func([Playlist], [], []),
  'savePlaylistByName' : IDL.Func([IDL.Text, IDL.Vec(TrackId)], [], []),
  'setActivePlaylist' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrackId = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Playlist = IDL.Vec(TrackId);
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getActivePlaylist' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
    'getPlaylist' : IDL.Func([], [IDL.Vec(TrackId)], ['query']),
    'getPlaylistByName' : IDL.Func([IDL.Text], [IDL.Vec(TrackId)], ['query']),
    'getPlaylistNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFavorites' : IDL.Func([IDL.Vec(TrackId)], [], []),
    'savePlaylist' : IDL.Func([Playlist], [], []),
    'savePlaylistByName' : IDL.Func([IDL.Text, IDL.Vec(TrackId)], [], []),
    'setActivePlaylist' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };